name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5 * * 1,5'
    - cron: '30 5 * * 2,4'

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "presentzeng@gmail.com"
          git config --local user.name "presentzeng"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
